# -*- coding: utf-8 -*-
"""Nayantara_Biswas_Script2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/102HBsYRRJJSIilDEK_7lu32Y8EUAoktD
"""

#Name: Nayantara Biswas
#Date: 04/07/2021
#Assignment: Script2_FinalProject
#Input: Online database of Life expectancy and GDP per capita in 2007 for all continents 
#Output: Interactive Scatterplot of the input as a web visualization

!pip install plotly
import plotly.express as px
gapminder = px.data.gapminder()
fig = px.scatter(gapminder.query("year==2007"), x="gdpPercap", y="lifeExp", size="pop", color="continent",
           hover_name="country", log_x=True, size_max=60)
fig.show()
!pip install chart_studio
import chart_studio
username = '' # your username
api_key = '' # your api key - go to profile > settings > regenerate key
chart_studio.tools.set_credentials_file(username=username, api_key=api_key)
import chart_studio.plotly as py
py.plot(fig, filename = 'gdp_per_cap', auto_open=True)