# -*- coding: utf-8 -*-
"""Script1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p_iplvI602S6M0YazKT7M16t9GryndUx
"""

#Name: Nayantara Biswas
#Date: 04/07/2021
#Assignemnt: Script1_FinalProject
#Input: URL: https://forecast.weather.gov/
#Output: Weather scraped in capital letters from latitude and longitude entered by user

# import required libraries
import requests
from bs4 import BeautifulSoup

# Create an empty list to store response
forecast = []

## Provide the latitude and longitude for the location you would like to check the forecast for
## Lat/lon in decimal degrees provided for Worcester, MA
lat=str(input("Please enter latitude (in degrees): "))
lon=str(input("Please enter longitude (in degrees): "))


# Create url for the requested location through string concatenation
url = 'https://forecast.weather.gov/MapClick.php?lat='+lat+"&lon="+lon
# Check if the URL exists
# print url

# Send request to retrieve the web-page using the get() function from the requests library
# The page variable stores the response from the web-page
page = requests.get(url)

# Create a BeautifulSoup object with the response from the URL
# Access contents of the web-page using .content
# html_parser is used since our page is in HTML format
soup=BeautifulSoup(page.content,"html.parser")

# Locate elements on page to be scraped
# findAll() locates all occurrences of div tag with the given class name
# stores it in the BeautifulSoup object
weather_forecast = soup.findAll("li", {"class": "forecast-tombstone"})

# Loop through the BeautifulSoup object to extract text text from every class instance using .text
# Store results in a list
for i in weather_forecast:
    i = i.text
    forecast.append(i)

# Print list to remove unicode characters
for day in forecast:
  day=day.replace('ClearLow','Clear Low')
  day=day.replace('SunnyHigh','Sunny High')
  day=day.replace('MondayNight','Monday Night')
  day=day.replace('CloudyLow','Cloudy Low')
  day=day.replace('TuesdayNight','Tuesday Night')
  day=day.replace('WednesdayNight','Wednesday Night')
  day=day.replace('Fogthen','Fog then')
  day=day.replace('PartlySunny','Partly Sunny')
  day=day.replace('SunnyAnd','Sunny And')
  day=day.replace('Breezy High','Breezy High')
  day=day.replace('ThursdayNight','Thursday Night')
  day=day.replace('Cloudythen','Cloudy then')
  day=day.replace('PatchyFogLow','Patchy Fog Low')
  day=day.replace('ShowersLikelyHigh','Showers Likely High')
  day=day.replace('ShowersLikelyLow','Showers Likely Low')
  day=day.upper()
  print(day)